User.new({provider: "email", uid: "admin1@boxfree.com", encrypted_password: "$2a$10$UUR5PxwcfsyLUVYxpLpb0OcUNPE0rZfEIzFmjk9lrZOmno0/I85YO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 16, current_sign_in_at: "2017-06-08 23:38:07", last_sign_in_at: "2017-05-23 14:52:19", current_sign_in_ip: "190.161.129.202", last_sign_in_ip: "200.104.168.150", confirmation_token: "yms1_1isprYErepMuJvy", confirmed_at: "2016-06-18 13:23:07", confirmation_sent_at: "2016-06-18 13:23:07", unconfirmed_email: nil, name: "Admin 1", nickname: nil, image: nil, email: "admin1@boxfree.com", tokens: {"3Gk6dD13yUIiP7xhkDbG2g"=>{"token"=>"$2a$10$Cti2Ji0fi7jSXe/FuM.k9ezdKubb0S4NAFXLcKu2wkwZQkEWBBpve", "expiry"=>1498174687}}, admin: true, super_admin: false, lastname: ""}).save(:validate => false)
User.new({provider: "email", uid: "admin2@boxfree.com", encrypted_password: "$2a$10$eJRg9h7kbV16hlO.MoflGuGsauGD.L7rLpKmkIYOp8MKN4Hy83umG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 10, current_sign_in_at: "2016-07-01 23:18:05", last_sign_in_at: "2016-06-30 13:55:23", current_sign_in_ip: "201.215.4.116", last_sign_in_ip: "190.44.26.236", confirmation_token: "zz1RPr2fKTfVstxijGwj", confirmed_at: "2016-06-18 13:23:07", confirmation_sent_at: "2016-06-18 13:23:07", unconfirmed_email: nil, name: "Admin 2", nickname: nil, image: nil, email: "admin2@boxfree.com", tokens: {"RKrcGRLG_0RPiLf66dM2fQ"=>{"token"=>"$2a$10$rrl3um/hMCxmefz1lQUaeudfdWspv6fOIL1yt77zd1Rb1khwY1EGG", "expiry"=>1468624685}}, admin: true, super_admin: false, lastname: ""}).save(:validate => false)
User.new({provider: "email", uid: "superadmin@boxfree.com", encrypted_password: "$2a$10$jgXmsb7lGkyq4MXNGG8h5.EdQjEVK1y0REInCMNXNp3K6T7/Y7jZK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 35, current_sign_in_at: "2017-06-06 19:22:23", last_sign_in_at: "2017-06-06 19:21:39", current_sign_in_ip: "200.120.108.8", last_sign_in_ip: "200.120.108.8", confirmation_token: "dLMT7KEhByZ6uXbqJFyw", confirmed_at: "2016-06-18 13:23:07", confirmation_sent_at: "2016-06-18 13:23:07", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "superadmin@boxfree.com", tokens: {"MVMFAo7xit1WrGTPuukE2A"=>{"token"=>"$2a$10$5zXR5ryuhBB7WCVlMgJHhecd/UABMe9joDodZ42Jgyx2QBrNw0Dqq", "expiry"=>1497986499}, "nNnXi1bcbKvJ2YxlatRDbg"=>{"token"=>"$2a$10$k5oIqrH3j/cfyiZKaBdeFuhbpbQI8aUVrEzFgVutrI6c0axCPPxJC", "expiry"=>1497986543}}, admin: false, super_admin: true, lastname: nil}).save(:validate => false)
User.new({provider: "email", uid: "fmaier@gmail.com", encrypted_password: "$2a$10$lmNhMhSTG8wGezMs3ms39O/quL2GOQsqnEt.g9EescGUshzLhxAC6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 17, current_sign_in_at: "2017-05-19 10:53:55", last_sign_in_at: "2017-05-18 21:39:52", current_sign_in_ip: "201.239.50.45", last_sign_in_ip: "200.83.227.228", confirmation_token: "uMw_tvYzUF2qGzywphpT", confirmed_at: "2016-06-18 18:02:30", confirmation_sent_at: "2016-06-18 18:02:30", unconfirmed_email: nil, name: "Felipe", nickname: nil, image: nil, email: "fmaier@gmail.com", tokens: {"xeeOfTa10rJSUo27i4vNQw"=>{"token"=>"$2a$10$crpUdwSPTozd0calWLgKzeBDLh43F3VtFr36RT7jcT0jpg8jK.PIq", "expiry"=>1496349553}, "pb-L8BYU4HWL0zJbKKjvwQ"=>{"token"=>"$2a$10$1kvCNm2H7w2zHtfNYxnq1uECsik.ICB3WJTMwsKmfeAg8mEYRIhtS", "expiry"=>1496353192}, "ShOjFU12j4YpjylxNsqE4w"=>{"token"=>"$2a$10$ASIWSXYZR1lSoKnuc8pks.ga4Aq7WkhoLSGD0DK3URNwCJD78Tu7O", "expiry"=>1496400835}}, admin: false, super_admin: false, lastname: "Maier"}).save(validate: false)
User.new({provider: "email", uid: "fmaier2@gmail.com", encrypted_password: "$2a$10$qS04IbPKDFJrUs8BE/yPT.Q1E0TZ3TCNmi5WZxLjxQ9Bb.LDKkzJW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "roSyKj2Dym5kZr2jTU8n", confirmed_at: nil, confirmation_sent_at: "2017-05-18 21:25:57", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "fmaier2@gmail.com", tokens: {}, admin: false, super_admin: false, lastname: nil},).save(validate: false)
User.new({provider: "email", uid: "fmaier3@gmail.com", encrypted_password: "$2a$10$tJPxD2WEGCAU5Ul.TXteY..NTNBqFm9IG/z5u2ZCZeMrD3y46QJta", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "BLBLyBsgNu6DKzr-XQSx", confirmed_at: nil, confirmation_sent_at: "2017-05-18 21:31:32", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "fmaier3@gmail.com", tokens: {}, admin: false, super_admin: false, lastname: nil}).save(validate: false)
User.new({provider: "email", uid: "fmaier4@gmail.com", encrypted_password: "$2a$10$iLSXHBdBdTsfuXqkMyDm4.in09zJDDQ8ncItzDiP/FiuOXyIaW3uq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "UGjx_2qoepHxQXrTsr57", confirmed_at: nil, confirmation_sent_at: "2017-05-18 21:33:35", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "fmaier4@gmail.com", tokens: {}, admin: false, super_admin: false, lastname: nil}).save(validate: false)
User.new({provider: "email", uid: "fmaier+test@gmail.com", encrypted_password: "$2a$10$zh1gB0jLtIU2xVov46nXTu.Ah60HtImnLp6GWHXmiE5dyOVDwODWW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, confirmation_token: "xugPmYVAkL335Me-7KQB", confirmed_at: "2017-05-18 21:39:39", confirmation_sent_at: "2017-05-18 21:35:10", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "fmaier+test@gmail.com", tokens: {"Sldxh5B4YXiPiEbQbF5AFw"=>{"token"=>"$2a$10$cSLQdPzmRIOg.xuLL1VEIulOCayHIXYxouhfMln0Kcj.nGfvj6STO", "expiry"=>1496353179}}, admin: false, super_admin: false, lastname: nil}).save(validate: false)
User.new({provider: "email", uid: "bmadain@gmail.com", encrypted_password: "$2a$10$Bu8T74vqhmTSX43tpNpgBe4368m65/R3Do0KVa5qZbjALfTC0uTjm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-06-08 23:25:29", last_sign_in_at: "2017-05-24 03:14:51", current_sign_in_ip: "186.9.134.53", last_sign_in_ip: "186.9.128.119", confirmation_token: "TgG5JHtasVUevEMsHso7", confirmed_at: "2017-05-24 03:14:40", confirmation_sent_at: "2017-05-24 03:14:11", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "bmadain@gmail.com", tokens: {"QbIJrElVd9_lyXtVx4egxQ"=>{"token"=>"$2a$10$2LtwuOXAz08eJu0CLpPzT.DimNZyT75qZzJ3cdKpP21svFJwsBcNe", "expiry"=>1498173929}}, admin: false, super_admin: false, lastname: nil}).save(validate: false)
User.new({provider: "email", uid: "pablo.ibanezd@gmail.com", encrypted_password: "$2a$10$hDc0pAsOYZBM3vMIVZUSkuaxAnIEQMoWvlSJVp1t0fMmd1j0IJek.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-06-01 23:20:10", last_sign_in_at: "2017-06-01 23:20:10", current_sign_in_ip: "201.215.30.246", last_sign_in_ip: "201.215.30.246", confirmation_token: "_gcpN9sGfQzTpS5UN6yE", confirmed_at: "2017-06-01 23:19:43", confirmation_sent_at: "2017-06-01 23:17:53", unconfirmed_email: nil, name: nil, nickname: nil, image: nil, email: "pablo.ibanezd@gmail.com", tokens: {"YcTVQArgRaw6dxisTKccnQ"=>{"token"=>"$2a$10$ClFlyGuE9bfgl16FG7gCFu1hlGYeTk0PpS59Y6iH..5BzLAHT2vNC", "expiry"=>1497568783}, "c_geaIloLBD6zBajSAl6ew"=>{"token"=>"$2a$10$XGt4wLo2zwTblahGLbp1VOEA7jKV7OFA.fFg5NAeBOM3bQRRgStrq", "expiry"=>1497568810}}, admin: false, super_admin: false, lastname: nil}).save(validate: false)

Drink.create!([
  {name: "Mistral 35°", description: "Pisco Mistral 35°", image_file_name: "mistral-35.jpg", image_content_type: "image/jpeg", image_file_size: 106201, image_updated_at: "2016-06-18 13:23:25", drink_category_id: 1},
  {name: "Alto del Carmen 35°", description: "Pisco Alto del Carmen 35°", image_file_name: "alto-del-carmen-35.jpg", image_content_type: "image/jpeg", image_file_size: 83240, image_updated_at: "2016-06-18 13:23:25", drink_category_id: 1},
  {name: "Capel 35°", description: "Pisco Capel 35°", image_file_name: "capel-35.jpg", image_content_type: "image/jpeg", image_file_size: 11959, image_updated_at: "2016-06-18 13:23:26", drink_category_id: 1},
  {name: "Ruta Norte 35°", description: "Pisco Ruta Norte 35°", image_file_name: "ruta-norte-35.jpg", image_content_type: "image/jpeg", image_file_size: 9395, image_updated_at: "2016-06-18 13:23:26", drink_category_id: 1},
  {name: "Pampero", description: "Ron Pampero Normal", image_file_name: "pampero.jpg", image_content_type: "image/jpeg", image_file_size: 7514, image_updated_at: "2016-06-18 13:23:26", drink_category_id: 2},
  {name: "Havana Club", description: "Ron Havana Club", image_file_name: "havana-club.png", image_content_type: "image/png", image_file_size: 54957, image_updated_at: "2016-06-18 13:23:26", drink_category_id: 2},
  {name: "Havana Club Añejo", description: "Ron Havana Club Añejo", image_file_name: "havana-club-añejo.jpg", image_content_type: "image/jpeg", image_file_size: 226150, image_updated_at: "2016-06-18 13:23:26", drink_category_id: 2},
  {name: "Cacique", description: "Ron Cacique", image_file_name: "cacique.jpg", image_content_type: "image/jpeg", image_file_size: 8413, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 2},
  {name: "José Cuervo", description: "Tequila José Cuervo", image_file_name: "jose-cuervo.jpg", image_content_type: "image/jpeg", image_file_size: 22865, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 3},
  {name: "Margarita", description: "Clasico Tequila Margarita", image_file_name: "margarita.jpg", image_content_type: "image/jpeg", image_file_size: 9988, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 3},
  {name: "Sun Rise", description: "Tequila Sun Rise", image_file_name: "sunrise.jpg", image_content_type: "image/jpeg", image_file_size: 131072, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 3},
  {name: "Campanario", description: "Pisco Sour Campanario", image_file_name: "campanario.jpg", image_content_type: "image/jpeg", image_file_size: 14718, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 4},
  {name: "Campanario Light", description: "Pisco Sour Campanario Light", image_file_name: "campanario-light.jpg", image_content_type: "image/jpeg", image_file_size: 12181, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 4},
  {name: "Capel", description: "Pisco Sour Capel", image_file_name: "capel.jpg", image_content_type: "image/jpeg", image_file_size: 19257, image_updated_at: "2016-06-18 13:23:27", drink_category_id: 4},
  {name: "Artesanos del Cochiguaz", description: "Pisco Sour Cochiguaz", image_file_name: "cochiguaz.jpg", image_content_type: "image/jpeg", image_file_size: 53365, image_updated_at: "2016-06-18 13:23:28", drink_category_id: 4},
  {name: "Mistral 40°", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 1},
  {name: "Alto del Carmen 40°", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 1},
  {name: "Johnnie Walker", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 5},
  {name: "Corona", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 6},
  {name: "Cristal", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 6},
  {name: "Mistral 35°", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 7},
  {name: "Alto del Carmen 35°", description: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, drink_category_id: 7}
])
DrinkCategory.create!([
  {name: "Pisco", description: nil},
  {name: "Ron", description: nil},
  {name: "Tequila", description: nil},
  {name: "Pisco Sour", description: nil},
  {name: "Whiskey", description: nil},
  {name: "Cerveza", description: nil},
  {name: "Botella", description: nil}
])
Pub.create!([
  {name: "Ex Amanda", description: "Centro Cultural", telephone1: nil, telephone2: nil, location: "Direccion ...22", image_logo_file_name: "amanda-logo.png", image_logo_content_type: "image/png", image_logo_file_size: 14705, image_logo_updated_at: "2016-06-18 13:23:07", user_id: 1, bank_name: "Banco De Chile", bank_account_type: "Cuenta Vista", bank_account_number: "123123", bank_account_rut: "asdasd", bank_account_email: "asdasd@adasdasd", order_index: 2},
  {name: "Candelaria", description: "Candelaria ...", telephone1: nil, telephone2: nil, location: "Sin direc...", image_logo_file_name: "candelaria-logo.png", image_logo_content_type: "image/png", image_logo_file_size: 8656, image_logo_updated_at: "2017-05-18 20:06:46", user_id: 2, bank_name: "Banco De Chile", bank_account_type: "Cuenta Vista", bank_account_number: "asdasdads", bank_account_rut: "asdasdasd", bank_account_email: "dasdadasd@dasdasd.com", order_index: 1},
  {name: "Ovo", description: "Dirección...", telephone1: nil, telephone2: nil, location: nil, image_logo_file_name: "OvoPremio_Grande.png", image_logo_content_type: "image/png", image_logo_file_size: 24469, image_logo_updated_at: "2017-05-18 20:40:43", user_id: 2, bank_name: nil, bank_account_type: nil, bank_account_number: nil, bank_account_rut: nil, bank_account_email: nil, order_index: 0}
])
PubDrink.create!([
  {price: 601, description: nil, drink_id: 5, pub_id: 2},
  {price: 1300, description: nil, drink_id: 2, pub_id: 1},
  {price: 1900, description: nil, drink_id: 5, pub_id: 1},
  {price: 2331, description: nil, drink_id: 10, pub_id: 1},
  {price: 1200, description: nil, drink_id: 3, pub_id: 1},
  {price: 3500, description: nil, drink_id: 4, pub_id: 1},
  {price: 2222, description: nil, drink_id: 3, pub_id: 1},
  {price: 2000, description: nil, drink_id: 3, pub_id: 1},
  {price: 3500, description: nil, drink_id: 2, pub_id: 3},
  {price: 3500, description: nil, drink_id: 1, pub_id: 3},
  {price: 4000, description: nil, drink_id: 17, pub_id: 3},
  {price: 4000, description: nil, drink_id: 18, pub_id: 3},
  {price: 4500, description: nil, drink_id: 5, pub_id: 3},
  {price: 5000, description: nil, drink_id: 19, pub_id: 3},
  {price: 2500, description: nil, drink_id: 20, pub_id: 3},
  {price: 2000, description: nil, drink_id: 21, pub_id: 3},
  {price: 35000, description: nil, drink_id: 22, pub_id: 3},
  {price: 30000, description: nil, drink_id: 23, pub_id: 3},
  {price: 3600, description: nil, drink_id: 15, pub_id: 2}
])
