require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::DrinkCategoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DrinkCategory. As you add validations to DrinkCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Api::DrinkCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all drink_categories as @drink_categories" do
      drink_category = DrinkCategory.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:drink_categories)).to eq([drink_category])
    end
  end

  describe "GET #show" do
    it "assigns the requested api_drink_category as @api_drink_category" do
      drink_category = DrinkCategory.create! valid_attributes
      get :show, {:id => drink_category.to_param}, valid_session
      expect(assigns(:api_drink_category)).to eq(drink_category)
    end
  end

  describe "GET #new" do
    it "assigns a new api_drink_category as @api_drink_category" do
      get :new, {}, valid_session
      expect(assigns(:api_drink_category)).to be_a_new(DrinkCategory)
    end
  end

  describe "GET #edit" do
    it "assigns the requested api_drink_category as @api_drink_category" do
      drink_category = DrinkCategory.create! valid_attributes
      get :edit, {:id => drink_category.to_param}, valid_session
      expect(assigns(:api_drink_category)).to eq(drink_category)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DrinkCategory" do
        expect {
          post :create, {:api_drink_category => valid_attributes}, valid_session
        }.to change(DrinkCategory, :count).by(1)
      end

      it "assigns a newly created api_drink_category as @api_drink_category" do
        post :create, {:api_drink_category => valid_attributes}, valid_session
        expect(assigns(:api_drink_category)).to be_a(DrinkCategory)
        expect(assigns(:api_drink_category)).to be_persisted
      end

      it "redirects to the created api_drink_category" do
        post :create, {:api_drink_category => valid_attributes}, valid_session
        expect(response).to redirect_to(DrinkCategory.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved api_drink_category as @api_drink_category" do
        post :create, {:api_drink_category => invalid_attributes}, valid_session
        expect(assigns(:api_drink_category)).to be_a_new(DrinkCategory)
      end

      it "re-renders the 'new' template" do
        post :create, {:api_drink_category => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested api_drink_category" do
        drink_category = DrinkCategory.create! valid_attributes
        put :update, {:id => drink_category.to_param, :api_drink_category => new_attributes}, valid_session
        drink_category.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested api_drink_category as @api_drink_category" do
        drink_category = DrinkCategory.create! valid_attributes
        put :update, {:id => drink_category.to_param, :api_drink_category => valid_attributes}, valid_session
        expect(assigns(:api_drink_category)).to eq(drink_category)
      end

      it "redirects to the api_drink_category" do
        drink_category = DrinkCategory.create! valid_attributes
        put :update, {:id => drink_category.to_param, :api_drink_category => valid_attributes}, valid_session
        expect(response).to redirect_to(drink_category)
      end
    end

    context "with invalid params" do
      it "assigns the api_drink_category as @api_drink_category" do
        drink_category = DrinkCategory.create! valid_attributes
        put :update, {:id => drink_category.to_param, :api_drink_category => invalid_attributes}, valid_session
        expect(assigns(:api_drink_category)).to eq(drink_category)
      end

      it "re-renders the 'edit' template" do
        drink_category = DrinkCategory.create! valid_attributes
        put :update, {:id => drink_category.to_param, :api_drink_category => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested api_drink_category" do
      drink_category = DrinkCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => drink_category.to_param}, valid_session
      }.to change(DrinkCategory, :count).by(-1)
    end

    it "redirects to the drink_categories list" do
      drink_category = DrinkCategory.create! valid_attributes
      delete :destroy, {:id => drink_category.to_param}, valid_session
      expect(response).to redirect_to(drink_categories_url)
    end
  end

end
